# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply_comment_facebook', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
