# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply_comment_facebook', '0006_auto_20180928_2307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devide',
            new_name='Device',
        ),
    ]
